Sdk 303
openmrs/openmrs-sdk pull request #218
Opened 2023-04-03 20:35 UTC by prateek27das

Optimising Artifact.java to reduce clutter

2023-04-04 16:39 UTC, ibacher requested changes
Thanks for this!

2023-04-04 16:39 UTC, ibacher commented on sdk-commons/src/main/java/org/openmrs/maven/plugins/model/Artifact.java
> +        StringBuilder sb = new StringBuilder();
Don't use a `StringBuilder` the string concatenation here is actually the right concatenation technique to use.

2023-04-04 16:40 UTC, ibacher commented on README.md
> +
It's probably better to do several branches off of master rather than branching off as-yet unmerged PRs.

2023-08-09 13:59 UTC, brandones commented
Closing as stale. @prateek27das please feel free to re-open if you continue working on it.

2023-08-09 13:59 UTC, closed without merging